joint_limits:
  left_j1:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -1.3962634015954636
    upper: 3.490658503988659
    velocity: 1.0
  left_j2:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -0.17453292519943295
    upper: 3.3161255787892263
    velocity: 1.0
  left_j3:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -1.5707963267948966
    upper: 1.5707963267948966
    velocity: 1.0
  left_j4:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -1.9198621771937625
    upper: 0.5235987755982988
    velocity: 1.0
  left_j5:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -1.5707963267948966
    upper: 1.5707963267948966
    velocity: 1.0
  left_j6:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -0.7853981633974483
    upper: 0.7853981633974483
    velocity: 1.0
  left_j7:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -1.5707963267948966
    upper: 1.5707963267948966
    velocity: 1.0
  revolute_1:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -0.7853981633974483
    upper: 0.7853981633974483
    velocity: 1.0
  revolute_2:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -0.17453292519943295
    upper: 0.7853981633974483
    velocity: 1.0
  right_j1:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -3.490658503988659
    upper: 1.3962634015954636
    velocity: 1.0
  right_j2:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -3.3161255787892263
    upper: 0.17453292519943295
    velocity: 1.0
  right_j3:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -1.5707963267948966
    upper: 1.5707963267948966
    velocity: 1.0
  right_j4:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -1.9198621771937625
    upper: 0.5235987755982988
    velocity: 1.0
  right_j5:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -1.5707963267948966
    upper: 1.5707963267948966
    velocity: 1.0
  right_j6:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -0.7853981633974483
    upper: 0.7853981633974483
    velocity: 1.0
  right_j7:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -1.5707963267948966
    upper: 1.5707963267948966
    velocity: 1.0
