[project]
name = "onshape2xacro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "onshape-robotics-toolkit",
    "tyro",
    "lxml",
    "pyyaml",
]

[project.scripts]
onshape2xacro = "onshape2xacro.cli:main"

[tool.uv]
package = true

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pytest",
]
