inertials:
  base_asm_1_j1_a_1:
    inertia:
      ixx: 0.0003815581873235676
      ixy: -2.6139495306208404e-06
      ixz: 5.273913880974552e-06
      iyy: 0.00043552208084642155
      iyz: 1.8470348346406805e-05
      izz: 0.0005587813403898795
    mass: 0.4447926906129235
    origin:
      rpy: 0 0 0
      xyz: 0.0004225630469408467 -0.001260592903001985 -0.017050354788607183
  j8_a_1:
    inertia:
      ixx: 3.4822794818669616e-06
      ixy: 8.797236764191286e-12
      ixz: -1.0008882782361765e-12
      iyy: 1.1924082631891956e-06
      iyz: 2.712461502063299e-07
      izz: 4.235205413822942e-06
    mass: 0.013487167794609461
    origin:
      rpy: 0 0 0
      xyz: -1.4579792310067617e-08 0.006316105358104163 -0.007521384669264204
  l1_asm_2_j1_c_1:
    inertia:
      ixx: 0.0004081537101965658
      ixy: -3.798234787971489e-05
      ixz: 3.2918245953564636e-06
      iyy: 0.0004986849092780867
      iyz: -9.07679657191065e-06
      izz: 0.0003269727066103081
    mass: 0.4178969984395271
    origin:
      rpy: 0 0 0
      xyz: -0.0007656379950508308 0.0021035872534912797 0.05625608353092415
  l2_asm_2_j2_a_1:
    inertia:
      ixx: 1.8522707495722326e-05
      ixy: 1.9769087813668725e-19
      ixz: -9.320708226103637e-06
      iyy: 3.372426743305397e-05
      iyz: 4.5077592504621886e-20
      izz: 2.872867412671202e-05
    mass: 0.041033930774329305
    origin:
      rpy: 0 0 0
      xyz: -0.04252570191751811 2.8395299357387205e-09 -0.011935014730564773
  l3_asm_2_boss_extrude31_1:
    inertia:
      ixx: 0.0013459322365069041
      ixy: 1.084837748070709e-08
      ixz: 2.1494218594446236e-06
      iyy: 0.0013780002360743418
      iyz: 4.243359956064711e-06
      izz: 0.00016479866731456067
    mass: 0.3129924668307467
    origin:
      rpy: 0 0 0
      xyz: -5.054142735176759e-05 -0.000697391146966823 0.09396176647281937
  l4_asm_2_j4_c_1:
    inertia:
      ixx: 0.00014143226671000248
      ixy: -3.823111942110899e-06
      ixz: 9.59891973858655e-07
      iyy: 8.057980790334107e-05
      iyz: 1.0192010812557755e-05
      izz: 0.00011495130832375389
    mass: 0.13403881192230088
    origin:
      rpy: 0 0 0
      xyz: 0.006279746602733015 0.0654386084383623 -0.03042113456557772
  l5_right_asm_1_j5_a_1:
    inertia:
      ixx: 9.245581486383435e-05
      ixy: -1.019659631349304e-06
      ixz: 8.916694243465607e-07
      iyy: 8.474788296378861e-05
      iyz: -9.5967889378606e-07
      izz: 6.05143627142807e-05
    mass: 0.13923890301693742
    origin:
      rpy: 0 0 0
      xyz: 0.00024714380823654715 -0.004022935478324458 -0.04365779257198262
  l6_urdf_2_j7_ab_1:
    inertia:
      ixx: 6.844381982409106e-05
      ixy: 2.747598103804076e-06
      ixz: 1.3066996244261359e-07
      iyy: 7.033214987142948e-05
      iyz: -1.8034053877709416e-06
      izz: 6.352929467751189e-05
    mass: 0.14244343107333207
    origin:
      rpy: 0 0 0
      xyz: -0.0021094827840471586 0.0009057774134606405 -0.03793488909004608
