joint_limits:
  right_j1:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: 1.2217304763960306
    upper: 6.1086523819801535
    velocity: 1.0
  right_j2:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -0.17453292519943295
    upper: 3.3161255787892263
    velocity: 1.0
  right_j3:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -1.5707963267948966
    upper: 1.5707963267948966
    velocity: 1.0
  right_j4:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -1.9198621771937625
    upper: 0.5235987755982988
    velocity: 1.0
  right_j5:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -1.5707963267948966
    upper: 1.5707963267948966
    velocity: 1.0
  right_j6:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -0.7853981633974483
    upper: 0.7853981633974483
    velocity: 1.0
  right_j7:
    damping: 0.0
    effort: 100.0
    friction: 0.0
    lower: -1.5707963267948966
    upper: 1.5707963267948966
    velocity: 1.0
